import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(request: NextRequest) {
  try {
    const { token, repoName } = await request.json();

    if (!token || !repoName) {
      return NextResponse.json({ error: 'Token and repo name are required' }, { status: 400 });
    }

    // 1. Get User info
    const userRes = await fetch('https://api.github.com/user', {
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json'
      }
    });

    if (!userRes.ok) {
      return NextResponse.json({ error: 'Invalid GitHub token' }, { status: 401 });
    }
    const user = await userRes.json();

    // 2. Create Repo
    const repoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: repoName,
        description: 'Generated by Config-to-App (C2A) Engine',
        private: false,
        auto_init: true
      })
    });

    if (!repoRes.ok) {
      const err = await repoRes.json();
      return NextResponse.json({ error: err.message || 'Failed to create repo' }, { status: repoRes.status });
    }
    const repo = await repoRes.json();

    // 3. Read app_config.json from our project
    const configPath = path.join(process.cwd(), 'app_config.json');
    const appConfigStr = fs.existsSync(configPath) ? fs.readFileSync(configPath, 'utf8') : '{}';

    // 4. Create files in the repo (using PUT /contents API for simplicity)
    const filesToCreate = [
      {
        path: 'app_config.json',
        content: appConfigStr
      },
      {
        path: 'README.md',
        content: `# ${repoName}\n\nThis is a generated application based on the C2A Engine.\n\n## Next Steps\n1. Clone the repository\n2. Run \`npm install\`\n3. Run \`npm run dev\``
      },
      {
        path: 'package.json',
        content: JSON.stringify({
          name: repoName,
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start"
          },
          dependencies: {
            next: "latest",
            react: "latest",
            "react-dom": "latest",
            tailwindcss: "latest"
          }
        }, null, 2)
      }
    ];

    for (const file of filesToCreate) {
      await fetch(`https://api.github.com/repos/${user.login}/${repoName}/contents/${file.path}`, {
        method: 'PUT',
        headers: {
          Authorization: `token ${token}`,
          Accept: 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          message: `Add ${file.path}`,
          content: Buffer.from(file.content).toString('base64')
        })
      });
    }

    return NextResponse.json({ url: repo.html_url }, { status: 200 });
  } catch (error: any) {
    console.error('GitHub export error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
