import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getAppConfig } from "@/lib/config-parser";
import AppShell from "@/components/AppShell";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth-options";
import { I18nProvider } from "@/lib/i18n-context";

const inter = Inter({ subsets: ["latin"] });

export async function generateMetadata(): Promise<Metadata> {
  const config = getAppConfig();
  return {
    title: config.appName,
    description: "Generated by Config-to-App Engine",
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const config = getAppConfig();

  return (
    <html lang="en" className={config.theme?.mode === "dark" ? "dark" : ""}>
      <body className={inter.className}>
        <I18nProvider config={config}>
          {session ? (
            <AppShell config={config}>{children}</AppShell>
          ) : (
            children
          )}
        </I18nProvider>
      </body>
    </html>
  );
}
