import { getServerSession } from "next-auth/next";
import { getAppConfig } from "@/lib/config-parser";
import { Server, Database, Shield, ArrowRight, Code, Zap, Layers } from "lucide-react";
import Link from "next/link";
import DashboardActions from "@/components/DashboardActions";
import LandingPageClient from "@/components/LandingPageClient";

export default async function Page() {
  const session = await getServerSession();
  const config = getAppConfig();
  
  if (session) {
    return (
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">
            Welcome to {config.appName}
          </h1>
          <p className="mt-2 text-gray-600 dark:text-gray-400">
            Your dynamic application generated by the Config-to-App Engine.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm flex flex-col items-center justify-center text-center">
            <Database className="w-10 h-10 text-blue-500 mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">{config.entities.length} Entities</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Configured in app_config.json</p>
          </div>
          
          <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm flex flex-col items-center justify-center text-center">
            <Shield className="w-10 h-10 text-green-500 mb-4" />
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Auth Enabled</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Secured via NextAuth</p>
          </div>

          <Link
            href="/builder"
            className="bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 p-6 rounded-xl border border-purple-200 dark:border-purple-800 shadow-sm flex flex-col items-center justify-center text-center hover:shadow-md hover:scale-[1.02] transition-all group"
          >
            <div className="w-10 h-10 bg-purple-100 dark:bg-purple-800/50 rounded-full flex items-center justify-center mb-4 group-hover:bg-purple-200 dark:group-hover:bg-purple-700/50 transition-colors">
              <Server className="w-5 h-5 text-purple-600 dark:text-purple-300" />
            </div>
            <h3 className="text-lg font-semibold text-purple-900 dark:text-purple-100">App Builder</h3>
            <p className="text-sm text-purple-600 dark:text-purple-400 mt-1">Add entities &amp; fields visually →</p>
          </Link>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">Quick Links</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {config.entities.map(entity => (
              <Link 
                key={entity.slug} 
                href={`/${entity.slug}`}
                className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg border border-blue-100 dark:border-blue-800 hover:bg-blue-100 dark:hover:bg-blue-900/40 transition-colors flex items-center"
              >
                <Database className="w-5 h-5 text-blue-600 dark:text-blue-400 mr-3" />
                <span className="font-medium text-blue-900 dark:text-blue-100">Manage {entity.name}</span>
              </Link>
            ))}
          </div>
          
          <DashboardActions />
        </div>
      </div>
    );
  }

  // --- LANDING PAGE ---
  return <LandingPageClient />;
}
